### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by Puyodead1** [TannerReynolds/ShareX-Custom-Upload-Server#5]
Discord is not embedding with https, i think it needs a robots.txt but i am not sure

**Comment by TannerReynolds** [comment]
I'm not sure what is causing your problem, discord embedding has always worked for me, with and without https. Are you sure https is properly configured?

**Comment by Puyodead1** [comment]
> I'm not sure what is causing your problem, discord embedding has always worked for me, with and without https. Are you sure https is properly configured?

Hm, Ye, I'm pretty sure it is. Not sure what is going on. Thanks for the reply
