### ISSUE TITLE
Text uploader failing

### ISSUE THREAD

**Issue by bushtarikgg** [TannerReynolds/ShareX-Custom-Upload-Server#7]
Following your tutorial, the text uploader is not passing the sharex test. Image, file, url shortener, are all working.

Thanks.

**Comment by TannerReynolds** [comment]
Please include a more detailed report. What error is ShareX giving you? Can I get a screenshot of your config - the sensitive data? Are you running the latest commit?

**Comment by bushtarikgg** [comment]
Latest commit.

https://share.busheezy.dev/6TBkX7
https://share.busheezy.dev/rWRncQ
https://share.busheezy.dev/qbWcDK

**Comment by TannerReynolds** [comment]
Please run the latest commit to see if it fixes your error

Also, are you sure SSL is properly configured?
https://i.imgur.com/jpyflwu.png

I see that you do not have a key.pem and cert.pem file in your src folder. Running a `secure` server without using key and cert pem files is only tested on Cloudflare's Flexible SSL method, which forces the https protocol without use of the files (Though it's not a completely secure connection regardless)

**Comment by bushtarikgg** [comment]
My SSL is working well. I'm routing it through nginx. I needed to set secure: true because you are forming URL's based off of this setting.

Thanks.

**Comment by bushtarikgg** [comment]
The latest commit is working well for me. Thanks!
