### ISSUE TITLE
URL redirects don't work

### ISSUE THREAD

**Issue by bushtarikgg** [TannerReynolds/ShareX-Custom-Upload-Server#9]
The actual html file is failing to redirect on any of my browsers.

Thanks.

**Comment by TannerReynolds** [comment]
What are the contents of the html file? And are you using the front end shortener or the `/api/short` route in ShareX?

**Comment by TannerReynolds** [comment]
Found error, it was caused by last update
https://github.com/TannerReynolds/ShareX-Custom-Upload-Server/commit/292fa48be29b1b569c6e41e9269445091affecd6
